package com.billing.billingsystem.model;
import java.time.Instant;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
@Table(name = "retryQueue")
@Getter
@Setter
@NoArgsConstructor
public class RetryQueue {
    
    @Id
    private UUID id; // generated by DB

    @ManyToOne(optional = false)
    @JoinColumn(name = "payment_id", nullable = false)
    private Payment payment;

    @Column(name = "retry_number", nullable = false)
    private int retryNumber = 0;

    @Column(name = "next_retry_time")
    private Instant nextRetryTime;

    @Column(name = "max_retries", nullable = false)
    private int maxRetries = 5;
}
